language: python
python:
  - "2.7"
install:  
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python -m pycoincap.tests.test_core --with-coverage --cover-package=pycoincap.core --cover-inclusive --cover-erase --cover-tests
after_success:
  - coveralls
