language: python
python:
  - "2.7"
# command to install dependencies
install:  
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
before_script: cd pycoincap
script:
  - python -m tests.test_core
after_success:
  - coveralls
