language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# command to run tests
script:
  - py.test -v --color=yes --exitfirst --showlocals --durations=5
  - python tests/test_core.py